---
- hosts: lampserver
  become: true
  gather_facts: false

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - include: handlers/handlers.yml

  tasks:
    - include: tasks/common.yml

    - include: tasks/apache.yml

    - include: tasks/php.yml

    - include: tasks/mysql.yml

    - include: tasks/composer.yml

    - include: tasks/drush.yml

    - include: tasks/drupal.yml
