---
- name: Check out drush 8.x branch
  git:
    repo: https://github.com/drush-ops/drush.git
    version: 8.x
    dest: /opt/drush

- name: Install Drush dependencies with composer
  shell: >
    /usr/local/bin/composer Install
    chdir=/opt/drush
    creates=/opt/drush/vendor/autoload.php

- name: Create drush bin Symbolic link
  file:
    src: /opt/drush/drush
    dest: /usr/local/bin/drush
    state: link
