---
- hosts: webservers
  become: true
  gather_facts: false
  tasks:
    - name: verify nginx service
      command: service nginx status
      changed_when: false

    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=1

- hosts: appservers
  become: true
  gather_facts: false
  tasks:
    - name: verify apache2 service
      command: service apache2 status
      changed_when: false

    - name: verify apache2 is listening on 80
      wait_for: port=80 timeout=1

- hosts: dbservers
  become: true
  gather_facts: false
  tasks:
    - name: verify mysql service
      command: service mysql status
      changed_when: false

    - name: verify mysql is listening on 3306
      wait_for: port=3306 timeout=1
